{% set name = "jupyterlab-topbar-text" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c243d4fa6e4766b24666688565d3059bc3d073e0a113442f369c360a6d7fdd54

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab =4
    - pip
    - python {{ python_min }}
  run:
    - jupyterlab ~=4.0
    - python >={{ python_min }},<4.0

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/jupyterlab-topbar-text/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-topbar-text\\package.json (exit 0) else (exit 1)          # [win]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-topbar/tree/main/packages/topbar-text-extension
  summary: JupyterLab extension to display arbitrary text in the top bar
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - fcollonval
