{% set name = "jupyterlab-topbar-text" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f2b552120f9611c8ebffdf284eecd30751b7a0517f7d74dde7e09e7046c3a1e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - jupyter-packaging >=0.10,<1
  run:
    - jupyterlab ~=3.0
    - jupyterlab-topbar >=0.6,<0.7
    - python >=3.6

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/jupyterlab-topbar-text/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-topbar-text\\package.json (exit 0) else (exit 1)          # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-topbar-text
  summary: JupyterLab extension to display arbitrary text in the top bar
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - fcollonval
